"""empty message

Revision ID: 65eaeafb0904
Revises: 9eb23abd5294
Create Date: 2025-08-14 12:28:56.157288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65eaeafb0904'
down_revision = '9eb23abd5294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.drop_column('part_of_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_of_day', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
