"""empty message

Revision ID: 9eb23abd5294
Revises: 101002a6ef17
Create Date: 2025-08-14 05:40:27.342711

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9eb23abd5294"
down_revision = "101002a6ef17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timezone",
                sa.String(length=64),
                nullable=False,
                server_default="UTC",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    # ### end Alembic commands ###
